#ifndef WINGMANN_DESIGN_PATTERNS_SOLID_DEPENDENCY_INVERSION_PRINCIPLE_PERSON_H
#define WINGMANN_DESIGN_PATTERNS_SOLID_DEPENDENCY_INVERSION_PRINCIPLE_PERSON_H

#include <string>

struct Person {
    std::string name;
};

#endif // WINGMANN_DESIGN_PATTERNS_SOLID_DEPENDENCY_INVERSION_PRINCIPLE_PERSON_H
