#ifndef WINGMANN_DESIGN_PATTERNS_SOLID_DEPENDENCY_INVERSION_PRINCIPLE_RELATIONSHIP_H
#define WINGMANN_DESIGN_PATTERNS_SOLID_DEPENDENCY_INVERSION_PRINCIPLE_RELATIONSHIP_H

enum class Relationship {
    Parent,
    Child,
    Sibling,
};

#endif // WINGMANN_DESIGN_PATTERNS_SOLID_DEPENDENCY_INVERSION_PRINCIPLE_RELATIONSHIP_H
